language: python
sudo: false
cache: pip

git:
  submodules: true

matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27

addons:
  apt:
    packages:
      - flake8
      - rstcheck

install:
  - pip install --ignore-installed --upgrade setuptools pip tox

script:
  - cd library
  - tox -vv
